export const homePageSelectors = {
    aTag: 'a',
    buttonTag: 'button',
    mainHeader: '.main-header',
    next: '.-next',
    optionTag: 'option',
    paginationBottom: '.pagination-bottom',
    previous: '.-previous',
    reactTable: '.ReactTable ',
    rowsPerPage: '[aria-label="rows per page"]',
    searchBox: '#searchBox',
    tBody: '.rt-tbody',
    tCell: '.rt-td',
    tColumnHeader: '[role="columnheader"]',
    tGroup: '.rt-tr-group',
    tRow: '.rt-tr',
    tHeader: '.rt-thead',
}
